### ISSUE TITLE
Docs: get rid of EBUSY error when starting storybook

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#1549]
When starting the storybook, the following error often occurs:
![Image](https://user-images.githubusercontent.com/33580481/247506957-dda4deba-73ea-4ffb-821b-034ebb39f9dc.png)

Previously we used [this hack](https://github.com/storybookjs/storybook/issues/19336#issuecomment-1280557403) to prevent it in the `managerWebpack` configuration in `main.js`.

However, Storybook 7 removed the 'managerWebpack' configuration: https://storybook.js.org/docs/react/builders/webpack#pre-bundled-assets-do-not-show-in-the-storybook-ui.

Currently we added `config.cache = { type: 'memory' };` to the `managerWebpack` configuration, this helps but does not get rid of the error completly. We have to find a more stable solution.

**Comment by gfellerph** [comment]
Fixed by moving to vite

**Comment by robcornelius** [comment]
I still see this exact error every single time I try to run storybook after running `npx storybook@latest init` in a fresh clone of a repo.
